// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DLQProducer is an autogenerated mock type for the DLQProducer type
type DLQProducer struct {
	mock.Mock
}

// Produce provides a mock function with given fields: ctx, key, value
func (_m *DLQProducer) Produce(ctx context.Context, key []byte, value []byte) error {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, []byte) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDLQProducer creates a new instance of DLQProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDLQProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *DLQProducer {
	mock := &DLQProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
